### ISSUE TITLE
Supporting diacritics in scenarios

### ISSUE THREAD

**Issue by MikevanDongen** [Augurk/Augurk#60] opened 2018-05-17 07:31 UTC
When scenarios contain characters with diacritics (like `é` or `ë`) they are shown as a square with a question mark (`�`) in the browser.

**Comment by jmezach** [comment] 2018-05-18 09:28
Sounds like an easy fix. Probably requires some escaping before displaying data. Would you mind submitting a pull request for this?

**Comment by MikevanDongen** [comment] 2018-05-23 06:14
I'll try to find the time, though I've found it a hassle to get Augurk to work on my local machine.

**Comment by jmezach** [comment] 2018-05-23 06:26
Interesting. Anything specific you are running into that we might be able to help out with? Anything we can improve on that front?

**Comment by marktaling** [comment] 2018-05-23 07:11
Could you provide a reproduction scenario for this issue? When I attempt to reproduce, I get the expected (correct) result in Chrome, Internet Explorer and even Edge.

![diacritics](https://user-images.githubusercontent.com/6681159/40408874-4fee4070-5e69-11e8-9f72-0dcbf206c8be.png)

**Comment by marktaling** [comment] 2018-06-06 06:19
@MikevanDongen Do you have a reproduction scenario for this? Otherwise we can't really assist with this issue.

**Comment by MikevanDongen** [comment] 2018-06-06 06:50
Hi @marktaling, sorry for the late response. Your screenshot 'flabbergasted' me somewhat, as it seems to disprove my issue.
In my case the feature-file contains `Scenario: Creëer nieuwe valide betrokkene` (language: NL) and the browser (Chrome) shows the following:
![image](https://user-images.githubusercontent.com/1590087/41021190-cff74918-6965-11e8-803b-4033b6bf21b6.png)
Though one explanation is that we're using version 2.2.0, which seems quite old. Apologies for not checking this before opening the issue. When I get the chance I'll update it, though it won't be for a while. If in your opinion this is the explanation, I don't mind you closing the issue.

**Comment by marktaling** [comment] 2018-06-06 06:58
Could you perhaps use the Developer Console to check how the scenario is transferred? Is it still correct in the Json?

**Comment by MikevanDongen** [comment] 2018-06-06 10:48
It seems to transfer the error:
![image](https://user-images.githubusercontent.com/1590087/41033640-95768336-6987-11e8-95d4-372a3c0e0a34.png)

**Comment by jmezach** [comment] 2018-06-06 10:58
What version of the command line are you currently using? Since version 3.0.0 of the command line we've been using a new Gherkin parser which may have fixed this issue. Maybe it's as simple as upgrading the command line to the latest version and publishing features files again.

**Comment by marktaling** [comment] 2018-06-06 11:16
I've tried reproducing this with version 2.3.1 of the CommandLine but that does not seem to be the issue. The only things I can think of 👍:
- you are running an older version of Augurk, as it uses an older datastorage it might mess this up
- the encoding of the file might mess up the commandline while reading

Sadly I am unable to reproduce it locally...

**Comment by MikevanDongen** [comment] 2018-06-06 11:51
The version of CommandLine is probably from the same era as Augurk. I'll try updating it and will report back (asap 😉).

**Comment by marktaling** [comment] 2018-07-19 11:30
Closing this issue for now. If this issue is still reproducable for you with the latest versions of Augurk, do not hesistate to reopen this issue.

**Closed by marktaling** 2018-07-19 11:30 UTC
